name: Notify File Changes

on:
  push:
    paths:
      - "backend/**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get file changes and notify owners
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/notify-changes.js')
            await script({ github, context, core })
